/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SimpleContract,
  SimpleContractInterface,
} from "../SimpleContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
    ],
    name: "setName",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "storeName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class SimpleContract__factory {
  static readonly abi = _abi;
  static createInterface(): SimpleContractInterface {
    return new Interface(_abi) as SimpleContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SimpleContract {
    return new Contract(address, _abi, runner) as unknown as SimpleContract;
  }
}
