/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ConfigInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "setGlobalLimits"
      | "setHouseFeePercentage"
      | "setMultiplierRange"
      | "setValidBettingDurations"
      | "setValidColours"
      | "setValidGridSizes"
      | "globalMaxBet"
      | "globalMinBet"
      | "houseFeePercentage"
      | "isValidBettingDuration"
      | "isValidColourCount"
      | "isValidGridSize"
      | "maxMultiplier"
      | "minMultiplier"
      | "owner"
      | "validBettingDurations"
      | "validColourCounts"
      | "validGridSizes"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setGlobalLimits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHouseFeePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMultiplierRange",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setValidBettingDurations",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setValidColours",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setValidGridSizes",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "globalMaxBet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "globalMinBet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "houseFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidBettingDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidColourCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidGridSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validBettingDurations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validColourCounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validGridSizes",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "setGlobalLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHouseFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMultiplierRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setValidBettingDurations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setValidColours",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setValidGridSizes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalMaxBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalMinBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "houseFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidBettingDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidColourCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidGridSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validBettingDurations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validColourCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validGridSizes",
    data: BytesLike
  ): Result;
}

export interface Config extends BaseContract {
  connect(runner?: ContractRunner | null): Config;
  waitForDeployment(): Promise<this>;

  interface: ConfigInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  setGlobalLimits: TypedContractMethod<
    [minBet: BigNumberish, maxBet: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHouseFeePercentage: TypedContractMethod<
    [feePercentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMultiplierRange: TypedContractMethod<
    [min: BigNumberish, max: BigNumberish],
    [void],
    "nonpayable"
  >;

  setValidBettingDurations: TypedContractMethod<
    [durations: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  setValidColours: TypedContractMethod<
    [colours: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  setValidGridSizes: TypedContractMethod<
    [sizes: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  globalMaxBet: TypedContractMethod<[], [bigint], "view">;

  globalMinBet: TypedContractMethod<[], [bigint], "view">;

  houseFeePercentage: TypedContractMethod<[], [bigint], "view">;

  isValidBettingDuration: TypedContractMethod<
    [duration: BigNumberish],
    [boolean],
    "view"
  >;

  isValidColourCount: TypedContractMethod<
    [count: BigNumberish],
    [boolean],
    "view"
  >;

  isValidGridSize: TypedContractMethod<[size: BigNumberish], [boolean], "view">;

  maxMultiplier: TypedContractMethod<[], [bigint], "view">;

  minMultiplier: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  validBettingDurations: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  validColourCounts: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  validGridSizes: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "setGlobalLimits"
  ): TypedContractMethod<
    [minBet: BigNumberish, maxBet: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setHouseFeePercentage"
  ): TypedContractMethod<[feePercentage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMultiplierRange"
  ): TypedContractMethod<
    [min: BigNumberish, max: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setValidBettingDurations"
  ): TypedContractMethod<[durations: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setValidColours"
  ): TypedContractMethod<[colours: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setValidGridSizes"
  ): TypedContractMethod<[sizes: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "globalMaxBet"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalMinBet"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "houseFeePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isValidBettingDuration"
  ): TypedContractMethod<[duration: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidColourCount"
  ): TypedContractMethod<[count: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidGridSize"
  ): TypedContractMethod<[size: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxMultiplier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minMultiplier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validBettingDurations"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "validColourCounts"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "validGridSizes"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  filters: {};
}
